on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: build libwing
      uses: actions/checkout@v4
      uses: actions-rust-lang/setup-rust-toolchain@v1
      run: cargo build

    - name: build wingmon
      uses: actions/checkout@v4
      uses: actions-rust-lang/setup-rust-toolchain@v1
      run: cargo build --bin wingmon

    - name: build wingschema
      uses: actions/checkout@v4
      uses: actions-rust-lang/setup-rust-toolchain@v1
      run: cargo build --bin wingschema
